### ISSUE TITLE
Sorry, animations for the "why workers" bar broke stuff

### ISSUE THREAD

**Issue by sgraden** [signalnerve/deploy.workers.cloudflare.com#50]
![image](https://user-images.githubusercontent.com/6685872/89224930-f6c6e380-d59e-11ea-8298-dfcfcfb7ce5e.png)

[Screen Recording 2020-08-03 at 3.34.17 PM.zip](https://github.com/signalnerve/deploy.workers.cloudflare.com/files/5018386/Screen.Recording.2020-08-03.at.3.34.17.PM.zip)

**Comment by signalnerve** [comment]
@sgraden https://github.com/signalnerve/deploy.workers.cloudflare.com/commit/49a7fdd6b98a225e16216ae09e3f7dc5a9faa986 should be an improvement on this, do you feel good about how this looks in production right now or should i continue to iterate on it?

**Comment by sgraden** [comment]
It seems to be a bit particular. at ~1316px the text is like against the border.

But overall on standard monitor sizes it seems to look good. I think dropping focus on this right now is fine and only if everything else is looking shiny can we look at it again

**Comment by signalnerve** [comment]
tweaked this a bit more in #82!
