### ISSUE TITLE
Let users reset the flow / go back

### ISSUE THREAD

**Issue by davidtsong** [signalnerve/deploy.workers.cloudflare.com#51]

**Comment by sgraden** [comment]
![image](https://user-images.githubusercontent.com/6685872/89609251-edf33d80-d83c-11ea-99b2-8c1ada3a5c5a.png)

Okay I bit the bullet and did it. Just a simple "Start over" in the bottom left of the page across from the feedback link. Same color and size as feedback link.

Link to icon: https://drive.google.com/open?id=15UpTKc15EN-QFLKckmB6OfJ8YsLyTlM2&authuser=sraden%40cloudflare.com&usp=drive_fs

**Comment by sgraden** [comment]
Slightly different placement for final success screen. 
![image](https://user-images.githubusercontent.com/6685872/89609376-4a565d00-d83d-11ea-8672-07be26c2ff0b.png)

**Comment by sgraden** [comment]
One note is just that this really feels like it's something for us more than a user, but I can see the edge cases where it might be useful
