### ISSUE TITLE
Authorize github is still attributed to "Signalnerve"

### ISSUE THREAD

**Issue by sgraden** [signalnerve/deploy.workers.cloudflare.com#52]

**Comment by sgraden** [comment]
https://docs.google.com/spreadsheets/d/1Fa5e8OniZXCPy3RdMR7B4i5zQpIOzcjhIMh9hfnJ_ZQ/edit#gid=0

**Comment by signalnerve** [comment]
started transferring this to cloudflare org, reached out to dane to figure out who has the ability to confirm that transfer

**Comment by sgraden** [comment]
Any motion on this? I know Dane is leaving for 2 weeks now :D

**Comment by signalnerve** [comment]
this is done!
