### ISSUE TITLE
cancelling github authorizing and navigating back to deploy flow gets in 1101 loop

### ISSUE THREAD

**Issue by sgraden** [signalnerve/deploy.workers.cloudflare.com#55]
May relate to: https://github.com/signalnerve/deploy.workers.cloudflare.com/issues/41

Cancelling github authorization and then using browser navigation to get back to the deploy process, ends in a 1101 error loop.

**Comment by sgraden** [comment]
if authed user cookie is set but no edge state json, it blows up

**Comment by sgraden** [comment]
https://docs.google.com/spreadsheets/d/1Fa5e8OniZXCPy3RdMR7B4i5zQpIOzcjhIMh9hfnJ_ZQ/edit#gid=0

**Comment by signalnerve** [comment]
@sgraden this may actually be a different issue than I thought it was in this comment

> if authed user cookie is set but no edge state json, it blows up

can you repro with a video so I can see what this is?

**Comment by sgraden** [comment]
Sent a video via chat cause it's too big
