### ISSUE TITLE
Null actions appearing on "click to enable actions"

### ISSUE THREAD

**Issue by sgraden** [signalnerve/deploy.workers.cloudflare.com#59]
@davidtsong may have more details

Click enable action
Got a 404 https://github.com/null/actions

https://docs.google.com/spreadsheets/d/1Fa5e8OniZXCPy3RdMR7B4i5zQpIOzcjhIMh9hfnJ_ZQ/edit#gid=0

**Comment by davidtsong** [comment]
nvm i think i will close this. this is probably from trying to use a repo that isnt setup for github actions

**Comment by sgraden** [comment]
Still something we should handle maybe better? idk if you can get an image of what happened?

**Comment by davidtsong** [comment]
can't reproduce dang
