### ISSUE TITLE
Removing "URL" parameter from link leaves you in same spot

### ISSUE THREAD

**Issue by sgraden** [signalnerve/deploy.workers.cloudflare.com#62]
Would have expected the template/404 page, but it just stayed in place after removing the GH URL from page URL. Open to discussion on this. Not crucial

**Comment by sgraden** [comment]
https://docs.google.com/spreadsheets/d/1Fa5e8OniZXCPy3RdMR7B4i5zQpIOzcjhIMh9hfnJ_ZQ/edit#gid=0

**Comment by signalnerve** [comment]
closing as this is probably an expected part of the state/caching stuff at this point (since this ticket was from 16 days ago). we can re-open with more specific descriptions of the problem w/ the new caching stuff in mind if we think it's bad still
